Models/Test.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DistanceLearning.Models
{
    public class Test
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }

        [ForeignKey("SubjectId")]
        public Subject Subject { get; set; }

        public int SubjectId { get; set; }

        [NotMapped]
        public bool completeForUser { get; set; }
    }
}

Models/TestResult.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DistanceLearning.Models
{
    public class TestResult
    {
        [Key]
        public int Id { get; set; }

        [ForeignKey("TestQuestionId")]
        public TestQuestion TestQuestion { get; set; }

        public int TestQuestionId
        {
            get; set;
        }

        [ForeignKey("UserId")]
        public User User { get; set; }

        public int UserId { get; set; }

        public bool Correct { get; set; }
    }
}

Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DistanceLearning.Models;
using Microsoft.AspNetCore.Authorization;

namespace DistanceLearning.Controllers
{
    [Authorize]
    public class SubjectsController : Controller
    {
        private readonly ApplicationContext _context;

        public SubjectsController(ApplicationContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "teacher,admin,student")]
        // GET: Subjects
        public async Task<IActionResult> Index()
        {
            if(User.IsInRole("admin"))
            {
                return View(await _context.Subjects.ToListAsync());
            }

            User user = _context.Users.Where(m => m.Email == User.Identity.Name).First();

            var query = from subject in _context.Subjects
                        join userSubject in _context.UsersSubject on subject.Id equals userSubject.SubjectId
                        where userSubject.UserId == user.Id
                        select subject;

            return View(await query.ToListAsync());
        }

        [Authorize(Roles = "admin")]
        // GET: Subjects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        [Authorize(Roles = "admin")]
        // GET: Subjects/Create
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        // POST: Subjects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                _context.Add(subject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(subject);
        }

        [Authorize(Roles = "admin")]
        // GET: Subjects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects.FindAsync(id);
            if (subject == null)
            {
                return NotFound();
            }
            return View(subject);
        }

        [Authorize(Roles = "admin")]
        // POST: Subjects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Subject subject)
        {
            if (id != subject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(subject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubjectExists(subject.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(subject);
        }

        [Authorize(Roles = "admin")]
        // GET: Subjects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        [Authorize(Roles = "admin")]
        // POST: Subjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subject = await _context.Subjects.FindAsync(id);
            _context.Subjects.Remove(subject);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SubjectExists(int id)
        {
            return _context.Subjects.Any(e => e.Id == id);
        }
    }
}

Controllers/TestQuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DistanceLearning.Models;
using Microsoft.AspNetCore.Authorization;

namespace DistanceLearning.Controllers
{
    [Authorize(Roles = "admin,teacher")]
    public class TestQuestionsController : Controller
    {
        private readonly ApplicationContext _context;

        public TestQuestionsController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: TestQuestions
        public async Task<IActionResult> Index(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Test test = _context.Tests.Where(m => m.Id == id).First();

            ViewData["TestId"] = id;
            ViewData["TestName"] = test.Name;

            var applicationContext = _context.TestQuestions.Include(t => t.Test).Where(t => t.TestId == id);
            return View(await applicationContext.ToListAsync());
        }

        // GET: TestQuestions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testQuestion = await _context.TestQuestions
                .Include(t => t.Test)
                .FirstOrDefaultAsync(m => m.TestQuestionId == id);
            if (testQuestion == null)
            {
                return NotFound();
            }

            return View(testQuestion);
        }

        // GET: TestQuestions/Create
        public IActionResult Create(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ViewData["TestId"] = id;

            return View();
        }

        // POST: TestQuestions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description,TestId,TrueAnswerScore")] TestQuestion testQuestion)
        {
            if (ModelState.IsValid)
            {
                _context.Add(testQuestion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = testQuestion.TestId } );
            }
            ViewData["TestId"] = new SelectList(_context.Tests, "Id", "Name", testQuestion.TestId);
            return View(testQuestion);
        }

        // GET: TestQuestions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testQuestion = await _context.TestQuestions.FindAsync(id);
            if (testQuestion == null)
            {
                return NotFound();
            }
            ViewData["TestId"] = new SelectList(_context.Tests, "Id", "Id", testQuestion.TestId);
            return View(testQuestion);
        }

        // POST: TestQuestions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Description,TestId,TrueAnswerId,TrueAnswerScore")] TestQuestion testQuestion)
        {
            if (id != testQuestion.TestQuestionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(testQuestion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TestQuestionExists(testQuestion.TestQuestionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TestId"] = new SelectList(_context.Tests, "Id", "Id", testQuestion.TestId);
            return View(testQuestion);
        }

        // GET: TestQuestions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testQuestion = await _context.TestQuestions
                .Include(t => t.Test)
                .FirstOrDefaultAsync(m => m.TestQuestionId == id);
            if (testQuestion == null)
            {
                return NotFound();
            }

            return View(testQuestion);
        }

        // POST: TestQuestions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var testQuestion = await _context.TestQuestions.FindAsync(id);
            _context.TestQuestions.Remove(testQuestion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TestQuestionExists(int id)
        {
            return _context.TestQuestions.Any(e => e.TestQuestionId == id);
        }
    }
}

Views/Tests/Create.cshtml
@model DistanceLearning.Models.Test

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Test</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubjectId" class="control-label"></label>
                <select asp-for="SubjectId" class ="form-control" asp-items="ViewBag.SubjectId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Tests/Delete.cshtml
@model DistanceLearning.Models.Test

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Test</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Tests/Details.cshtml
@model DistanceLearning.Models.Test

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Test</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Tests/Edit.cshtml
@model DistanceLearning.Models.Test

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Test</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubjectId" class="control-label"></label>
                <select asp-for="SubjectId" class="form-control" asp-items="ViewBag.SubjectId"></select>
                <span asp-validation-for="SubjectId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Tests/Index.cshtml
@model IEnumerable<DistanceLearning.Models.Test>

@{
    ViewData["Title"] = "Index";
}

@{
    if (User.IsInRole("admin"))
    {
        <h1>Test List</h1>
    }
    else
    {
        <h1>Tests of the subject "@ViewData["Subject"]"</h1>
    }
}


@{
    if (User.IsInRole("admin") || User.IsInRole("teacher"))
    {
        <p>
            <a asp-action="Create">Create New Test</a>
        </p>}
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @{
                        if (User.IsInRole("admin") || User.IsInRole("teacher"))
                        {
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                            <a asp-controller="TestQuestions" asp-action="Index" asp-route-id="@item.Id">Show questions</a>
                            <a asp-action="ShowStudentResults" asp-route-id="@item.Id">Show Student Results</a>
                        }
                        if (User.IsInRole("student"))
                        {
                            if (item.completeForUser == true)
                            {
                <p>Test Complete</p>
                            }
                            else
                            {
                                <a asp-action="TakeTest" asp-route-id="@item.Id">Take the Test</a>
                            }
                        }
                    }

                </td>
            </tr>
        }
    </tbody>
</table>

@{
    if (!User.IsInRole("admin"))
    {
        <div>
            <a asp-action="Index" asp-controller="Subjects">Back to Subjects List</a>
        </div>
    }
}

Views/Tests/ShowStudentResults.cshtml
@model IEnumerable<DistanceLearning.Models.TestStudentResultTable>

@{
    ViewData["Title"] = "Student Results";
}

<h1>Student Results</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Student
            </th>
            <th>
                Results
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.User.Name)
                </td>
                <td>
                    @item.Score / @ViewData["TotalScore"]
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Tests/TestResults.cshtml
@{
    ViewData["Title"] = "Test Results";
}

<h1>Test Results</h1>

<h4>Test</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <h3>@ViewData["Scores"] / @ViewData["TotalScore"]</h3>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Tests/takeTest.cshtml
@model TestAnswerForm 


@{
    ViewData["Title"] = "takeTest";
}

<h1>Test</h1>

<h4>@ViewData["QuestionDescription"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="takeTest">
            <input type="hidden" name="Question" value="@Model.Question" />
            <span asp-validation-for="Response" class="text-danger"></span>
            @foreach (var answer in Model.Answers)
            {
                //<input type="radio" asp-for="Response" value="@answer.TestAnswerVariantId" />@answer.Description<br />
                <div class="custom-control custom-radio">
                    <input type="radio" class="custom-control-input" asp-for="Response" id="Variant_@answer.TestAnswerVariantId" value="@answer.TestAnswerVariantId">
                    <label class="custom-control-label" for="Variant_@answer.TestAnswerVariantId">@answer.Description</label>
                </div>
            }
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Subjects" asp-action="Index" asp-route-id="@ViewData["SubjectId"]">Back to Test List</a>
</div>